"""Migração inicial

Revision ID: 24818673f3a2
Revises: 
Create Date: 2026-08-27 07:56:42.736737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24818673f3a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('estilo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monstro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.Enum('Jovem', 'Adulto', 'Apex', name='categoriamonstro'), nullable=False),
    sa.Column('vigor_base', sa.Integer(), nullable=False),
    sa.Column('vigor_atual', sa.Integer(), nullable=False),
    sa.Column('historia', sa.Text(), nullable=True),
    sa.Column('alvos', sa.Text(), nullable=True),
    sa.Column('dieta', sa.String(length=100), nullable=True),
    sa.Column('habitat', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnica',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traco',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('utensilio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('alcance', sa.String(length=50), nullable=True),
    sa.Column('durabilidade_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('vigor_max', sa.Integer(), nullable=False),
    sa.Column('vigor_atual', sa.Integer(), nullable=False),
    sa.Column('voce_e', sa.Text(), nullable=True),
    sa.Column('tenta_ser', sa.Text(), nullable=True),
    sa.Column('feras_familiares', sa.Text(), nullable=True),
    sa.Column('prato_tipico', sa.String(length=100), nullable=True),
    sa.Column('tempero_tipico', sa.String(length=100), nullable=True),
    sa.Column('infancia_criacao', sa.Text(), nullable=True),
    sa.Column('iniciacao_como_feral', sa.Text(), nullable=True),
    sa.Column('ambicao', sa.Text(), nullable=True),
    sa.Column('conexao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monstro_estilo',
    sa.Column('monstro_id', sa.Integer(), nullable=False),
    sa.Column('estilo_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estilo_id'], ['estilo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monstro_id'], ['monstro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monstro_id', 'estilo_id')
    )
    op.create_table('monstro_habilidade',
    sa.Column('monstro_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monstro_id'], ['monstro.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monstro_id', 'habilidade_id')
    )
    op.create_table('monstro_parte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monstro_id', sa.Integer(), nullable=False),
    sa.Column('tecnica_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('alcance', sa.String(length=50), nullable=True),
    sa.Column('durabilidade_max', sa.Integer(), nullable=False),
    sa.Column('durabilidade_atual', sa.Integer(), nullable=False),
    sa.Column('se_quebrado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['monstro_id'], ['monstro.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monstro_traco',
    sa.Column('monstro_id', sa.Integer(), nullable=False),
    sa.Column('traco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monstro_id'], ['monstro.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traco_id'], ['traco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monstro_id', 'traco_id')
    )
    op.create_table('utensilio_tecnica',
    sa.Column('utensilio_id', sa.Integer(), nullable=False),
    sa.Column('tecnica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utensilio_id'], ['utensilio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('utensilio_id', 'tecnica_id')
    )
    op.create_table('feral_condicao',
    sa.Column('feral_id', sa.Integer(), nullable=False),
    sa.Column('condicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['condicao_id'], ['condicao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feral_id'], ['feral.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feral_id', 'condicao_id')
    )
    op.create_table('feral_estilo',
    sa.Column('feral_id', sa.Integer(), nullable=False),
    sa.Column('estilo_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estilo_id'], ['estilo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feral_id'], ['feral.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feral_id', 'estilo_id')
    )
    op.create_table('feral_habilidade',
    sa.Column('feral_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feral_id'], ['feral.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feral_id', 'habilidade_id')
    )
    op.create_table('feral_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feral_id', sa.Integer(), nullable=False),
    sa.Column('utensilio_id', sa.Integer(), nullable=False),
    sa.Column('durabilidade_atual', sa.Integer(), nullable=False),
    sa.Column('se_quebrado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['feral_id'], ['feral.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utensilio_id'], ['utensilio.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feral_traco',
    sa.Column('feral_id', sa.Integer(), nullable=False),
    sa.Column('traco_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feral_id'], ['feral.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traco_id'], ['traco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feral_id', 'traco_id')
    )
    op.create_table('feral_inventario_tecnica',
    sa.Column('feral_inventario_id', sa.Integer(), nullable=False),
    sa.Column('tecnica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feral_inventario_id'], ['feral_inventario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnica_id'], ['tecnica.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feral_inventario_id', 'tecnica_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feral_inventario_tecnica')
    op.drop_table('feral_traco')
    op.drop_table('feral_inventario')
    op.drop_table('feral_habilidade')
    op.drop_table('feral_estilo')
    op.drop_table('feral_condicao')
    op.drop_table('utensilio_tecnica')
    op.drop_table('monstro_traco')
    op.drop_table('monstro_parte')
    op.drop_table('monstro_habilidade')
    op.drop_table('monstro_estilo')
    op.drop_table('feral')
    op.drop_table('utensilio')
    op.drop_table('usuario')
    op.drop_table('traco')
    op.drop_table('tecnica')
    op.drop_table('monstro')
    op.drop_table('habilidade')
    op.drop_table('estilo')
    op.drop_table('condicao')
    # ### end Alembic commands ###
